---
jobs:
  enforce:
    name: Enforce Repository Rulesets
    runs-on: ubuntu-24.04
    steps:
      # Checkout the repository
      # https://github.com/actions/checkout
      - name: Checkout the repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      # Set up uv
      # https://github.com/astral-sh/setup-uv
      - name: Set up uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
      # Execute the enforcement script
      - name: Execute enforcement script
        run: |
          uv run main.py \
            --exclude-required-check Analyze \
            --exclude-required-check dependency-review \
            --token ${{ secrets.GH_ENFORCE_PAT }} \
            --user MattKobayashi
name: Enforce Repository Rulesets
on:
  schedule:
    - cron: "20 4 * * *"
  workflow_dispatch:
permissions:
  contents: read
