---
jobs:
  enforce:
    name: Enforce Repository Rulesets
    runs-on: ubuntu-24.04
    steps:
      # Harden the runner (Audit all outbound calls)
      # https://github.com/step-security/harden-runner
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit
      # Checkout the repository
      # https://github.com/actions/checkout
      - name: Checkout the repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      # Set up uv
      # https://github.com/astral-sh/setup-uv
      - name: Set up uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
      # Execute the enforcement script
      - name: Execute enforcement script
        run: |
          uv run main.py \
            --exclude-required-check Analyze \
            --exclude-required-check dependency-review \
            --token ${{ secrets.GH_ENFORCE_PAT }} \
            --user MattKobayashi
name: Enforce Repository Rulesets
on:
  schedule:
    - cron: "20 4 * * *"
  workflow_dispatch:
permissions:
  contents: read
